<a href="https://colab.research.google.com/github/Goutam-P/dtsc/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
url= 'https://github.com/Goutam-P/dtsc/blob/main/old.adult.names'

--2024-11-01 15:31:15--  https://github.com/Goutam-P/dtsc/blob/main/old.adult.names
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘old.adult.names’

old.adult.names         [ <=>                ] 337.31K  --.-KB/s    in 0.06s

Last-modified header missing -- time-stamps turned off.
2024-11-01 15:31:15 (5.46 MB/s) - ‘old.adult.names’ saved [345407]

In [6]:
import pandas as pd
url= 'https://raw.githubusercontent.com/Goutam-P/dtsc/refs/heads/main/adult.data'
df=pd.read_csv(url)
df.head(5)

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K